"""
Updated Negotiation Chatbot with RAG Enhancement
Now uses LangChain + ChromaDB for smarter answers
"""

import google.generativeai as genai
import os
from dotenv import load_dotenv
from typing import Dict, List, Optional

load_dotenv()

# Configure Gemini 2.0 Flash
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

class NegotiationChatbot:
    """
    AI-powered negotiation assistant using Google Gemini 2.5 Flash + RAG
    
    Flow:
    1. Rules analyze SLA → Generate intents
    2. RAG retrieves relevant tactics from vector DB
    3. LLM creates negotiation script with retrieved context
    4. User asks follow-up questions (enhanced with RAG)
    """
    
    @staticmethod
    def check_missing_fields(sla_data: Dict) -> Dict:
        """
        Check which critical fields are missing from contract
        Returns dict with missing fields and user-friendly message
        """
        critical_fields = {
            'interest_rate': 'Interest Rate / APR',
            'monthly_payment': 'Monthly Payment',
            'down_payment': 'Down Payment',
            'lease_term_months': 'Lease/Loan Term',
            'mileage_allowance': 'Mileage Allowance (for leases)',
            'overage_charge': 'Overage Charge per Mile',
            'early_termination_fee': 'Early Termination Fee',
            'late_fee': 'Late Payment Fee',
            'purchase_option': 'Purchase Option / Buyout Price',
            'residual_value': 'Residual Value'
        }
        
        missing = []
        for field, display_name in critical_fields.items():
            if not sla_data.get(field):
                missing.append(display_name)
        
        if missing:
            return {
                "has_missing_fields": True,
                "missing_fields": missing,
                "message": f"⚠️ Please provide the following missing contract details:\n\n" + 
                          "\n".join([f"• {field}" for field in missing])
            }
        else:
            return {
                "has_missing_fields": False,
                "missing_fields": [],
                "message": "✓ All critical contract fields are present"
            }
    
    @staticmethod
    def generate_simple_negotiation_message(
        vehicle_data: Optional[Dict],
        sla_data: Dict,
        user_intent: str
    ) -> str:
        """
        Generate a simple negotiation message (Quick Message Mode)
        User provides their own intent
        
        Args:
            vehicle_data: Vehicle information
            sla_data: Contract SLA data
            user_intent: User's negotiation goal (e.g., "lower monthly payment to $400")
        
        Returns:
            2-3 sentence professional negotiation message
        """
        
        # Format vehicle info
        vehicle_info = "Unknown vehicle"
        if vehicle_data:
            make = vehicle_data.get('make', 'Unknown')
            model = vehicle_data.get('model', 'Unknown')
            year = vehicle_data.get('year', 'Unknown')
            vehicle_info = f"{year} {make} {model}"
        
        # Format contract terms
        contract_terms = []
        if sla_data.get('interest_rate'):
            contract_terms.append(f"APR: {sla_data['interest_rate']}")
        if sla_data.get('monthly_payment'):
            contract_terms.append(f"Monthly Payment: {sla_data['monthly_payment']}")
        if sla_data.get('lease_term_months'):
            contract_terms.append(f"Term: {sla_data['lease_term_months']} months")
        
        contract_summary = ", ".join(contract_terms) if contract_terms else "Terms not fully specified"
        
        prompt = f"""You are helping a customer negotiate a car lease/loan.

Context:
Vehicle: {vehicle_info}
Contract terms: {contract_summary}

Negotiation goal: {user_intent}

Write a polite, professional negotiation message in 2–3 sentences that the customer can use when speaking with the dealer.
Be specific and reference actual numbers from the contract."""
        
        try:
            model = genai.GenerativeModel('gemini-2.5-flash')
            response = model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            return f"Error generating negotiation message: {str(e)}"
    
    @staticmethod
    def generate_comprehensive_negotiation_script(
        sla_data: Dict,
        negotiation_intents: List[Dict],
        analysis: Dict,
        vehicle_data: Optional[Dict] = None,
        use_rag: bool = True  # NEW: Enable RAG by default
    ) -> str:
        """
        Generate comprehensive negotiation script
        NOW WITH RAG: Retrieves relevant tactics from vector database
        
        Args:
            sla_data: Contract SLA data
            negotiation_intents: List of intents generated by NegotiationRules
            analysis: Full analysis with fairness score and red flags
            vehicle_data: Vehicle information
            use_rag: Whether to use RAG enhancement (default: True)
        
        Returns:
            Professional, detailed negotiation script with RAG-retrieved tactics
        """
        
        # ✅ NEW: Use RAG if enabled
        if use_rag:
            try:
                from app.core.negotiation_rag_enhanced import get_negotiation_rag
                rag = get_negotiation_rag()
                return rag.enhance_script_generation(
                    sla_data=sla_data,
                    negotiation_intents=negotiation_intents,
                    analysis=analysis,
                    vehicle_data=vehicle_data
                )
            except Exception as e:
                print(f"RAG enhancement failed, falling back to standard: {e}")
                # Fall through to standard generation
        
        # Standard generation (fallback if RAG fails or disabled)
        vehicle_info = "Vehicle not specified"
        if vehicle_data:
            vehicle_info = f"{vehicle_data.get('year')} {vehicle_data.get('make')} {vehicle_data.get('model')}"
        
        intents_formatted = []
        for idx, intent in enumerate(negotiation_intents, 1):
            intents_formatted.append(f"""
Intent {idx} - {intent['priority']} PRIORITY:
Field: {intent['field']}
Current Value: {intent['current_value']}
Target Value: {intent['target_value']}
Market Benchmark: {intent['market_benchmark']}
Reasoning: {intent['reasoning']}
Negotiation Leverage: {intent['negotiation_leverage']}
""")
        
        intents_summary = "\n".join(intents_formatted)
        red_flags = analysis.get('red_flags', [])
        fairness_score = analysis.get('fairness_score', 'N/A')
        rating = analysis.get('rating', 'Unknown')
        red_flags_text = "\n".join([f"• {flag}" for flag in red_flags]) if red_flags else "• None identified"
        
        prompt = f"""You are a professional Car Lease Negotiation Expert with 15+ years of automotive finance experience.

VEHICLE: {vehicle_info}

CONTRACT ANALYSIS:
Fairness Score: {fairness_score}/100 ({rating})

RED FLAGS:
{red_flags_text}

NEGOTIATION INTENTS:
{intents_summary}

CURRENT CONTRACT TERMS:
- Interest Rate/APR: {sla_data.get('interest_rate', 'Not specified')}
- Monthly Payment: {sla_data.get('monthly_payment', 'Not specified')}
- Down Payment: {sla_data.get('down_payment', 'Not specified')}
- Lease Term: {sla_data.get('lease_term_months', 'Not specified')} months
- Mileage Allowance: {sla_data.get('mileage_allowance', 'Not specified')}
- Overage Charge: {sla_data.get('overage_charge', 'Not specified')}
- Early Termination Fee: {sla_data.get('early_termination_fee', 'Not specified')}
- Late Fee: {sla_data.get('late_fee', 'Not specified')}

TASK:
Generate a complete, professional negotiation script that the customer can use directly with the dealer.

REQUIREMENTS:
1. Polite but firm tone - professional and assertive
2. Address ALL intents prioritized by CRITICAL → HIGH → MEDIUM → LOW
3. For each negotiation point:
   - State current term clearly
   - Cite market benchmark
   - Make concrete counter-offer using target value
   - Explain why this is fair
4. Structure:
   - Opening: Professional greeting
   - Issues: Present each point (grouped by priority)
   - Counter-offers: Specific proposals
   - Closing: Next steps
5. Ready to use (5-7 paragraphs)
6. Use actual numbers from contract

Generate the script:"""
        
        try:
            model = genai.GenerativeModel('gemini-2.5-flash')
            response = model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            return f"Error generating negotiation script: {str(e)}"
    
    @staticmethod
    def answer_followup_question(
        user_question: str,
        sla_data: Dict,
        negotiation_intents: List[Dict],
        analysis: Dict,
        vehicle_data: Optional[Dict] = None,
        conversation_history: Optional[List[Dict]] = None,
        use_rag: bool = True  # NEW: Enable RAG by default
    ) -> str:
        """
        Answer follow-up questions about negotiation strategy
        NOW WITH RAG: Retrieves relevant tactics and benchmarks from vector database
        
        Args:
            user_question: User's question
            sla_data: Contract data
            negotiation_intents: Generated intents
            analysis: Analysis results
            vehicle_data: Vehicle info
            conversation_history: Previous messages
            use_rag: Whether to use RAG enhancement (default: True)
        
        Returns:
            Helpful, specific answer enhanced with RAG-retrieved context
        """
        
        # ✅ NEW: Use RAG if enabled
        if use_rag:
            try:
                from app.core.negotiation_rag_enhanced import get_negotiation_rag
                rag = get_negotiation_rag()
                return rag.enhance_answer(
                    user_question=user_question,
                    sla_data=sla_data,
                    negotiation_intents=negotiation_intents,
                    analysis=analysis,
                    vehicle_data=vehicle_data,
                    conversation_history=conversation_history
                )
            except Exception as e:
                print(f"RAG enhancement failed, falling back to standard: {e}")
                # Fall through to standard generation
        
        # Standard answer generation (fallback)
        import re
        income_match = re.search(r'\$?\s*(\d+(?:,\d+)?)\s*(?:per month|monthly|/month|a month)', user_question.lower())
        user_income = None
        if income_match:
            user_income = float(income_match.group(1).replace(',', ''))
        
        intents_summary = []
        for intent in negotiation_intents[:5]:
            intents_summary.append(
                f"- {intent['field']}: Current {intent['current_value']}, "
                f"Target {intent['target_value']} (Market: {intent['market_benchmark']})"
            )
        
        intents_text = "\n".join(intents_summary)
        
        conversation_context = ""
        if conversation_history:
            recent_messages = conversation_history[-3:]
            conversation_context = "RECENT CONVERSATION:\n"
            for msg in recent_messages:
                role = msg.get("role", "user")
                content = msg.get("content", "")
                conversation_context += f"{role.upper()}: {content}\n"
        
        affordability_context = ""
        if user_income:
            monthly_payment = sla_data.get('monthly_payment')
            if monthly_payment:
                from app.core.negotiation_rules import NegotiationRules
                payment_amount = NegotiationRules._extract_number(monthly_payment)
                if payment_amount:
                    payment_percentage = (payment_amount / user_income) * 100
                    affordability_context = f"""
AFFORDABILITY ANALYSIS:
Monthly Income: ${user_income:,.0f}
Monthly Payment: ${payment_amount:.2f}
Payment Percentage: {payment_percentage:.1f}% of income
Recommended Maximum: 15% of income (${user_income * 0.15:.2f})
Status: {"✓ AFFORDABLE" if payment_percentage <= 15 else "⚠️ OVER BUDGET"}
"""
        
        prompt = f"""You are a car lease/loan negotiation expert.

VEHICLE: {vehicle_data.get('year', '')} {vehicle_data.get('make', '')} {vehicle_data.get('model', '')}

CONTRACT:
- Interest Rate: {sla_data.get('interest_rate', 'Not specified')}
- Monthly Payment: {sla_data.get('monthly_payment', 'Not specified')}
- Term: {sla_data.get('lease_term_months', 'Not specified')} months
- Fairness Score: {analysis.get('fairness_score', 'N/A')}/100

KEY INTENTS:
{intents_text}

{affordability_context}

{conversation_context}

QUESTION: {user_question}

Provide a helpful, specific answer (2-5 sentences). If about tactics, provide concrete strategies. If about terms, reference market standards.

Answer:"""
        
        try:
            model = genai.GenerativeModel('gemini-2.5-flash')
            response = model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            return f"Error: {str(e)}"
    
    @staticmethod
    def explain_intent(intent: Dict) -> str:
        """
        Explain a single negotiation intent in user-friendly language
        """
        
        prompt = f"""Explain this negotiation point to a customer in simple, friendly language:

Field: {intent['field']}
Current Value: {intent['current_value']}
Target Value: {intent['target_value']}
Market Benchmark: {intent['market_benchmark']}
Reasoning: {intent['reasoning']}

Write 2-3 sentences explaining:
1. What this term means
2. Why the current value is problematic
3. What they should ask for instead

Be encouraging and practical."""
        
        try:
            model = genai.GenerativeModel('gemini-2.5-flash')
            response = model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            return f"Error: {str(e)}"